# Generated by Django 4.2.4 on 2023-09-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='caption',
            new_name='message',
        ),
        migrations.AddField(
            model_name='shop',
            name='welcome_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
